spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/scheduled_task?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true